services:
  - type: web
    name: cliq
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn social_book.wsgi:application --bind 0.0.0.0:$PORT"
    rootDir: social_book
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "cliq-v0o1.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.0"
